In [2]:
# We already know anout the Dropout Layer in the ANN model, this randomly selects some of the nuerons that will be firing to the 
# next hidden layer for a specific epoch and the selected nuerons will be different everytime for a new epoch,
# This way of data regularization is called Dropout Regularization and it quite often used for preventing overfitting and hence low bias of training 
# Data in the Deep Learning Model.
# Dropout Regularization increases the model accuracy

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('sonar.csv')
df

0.02  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167   0.018  0.0084  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

      0.009  0.0032  R  
0    0.0052  0.0044  R  
1    0.0095  0.0078  R  
2    0.0040  0.0117  R  
3    0.0107  0.0094  R  
4    0.0051  0.0062  R  
..      ...     ... ..  
202  0.0193  0.0157  M  
203  0.0062  0.0067  M  
204  0.0077  0.0031  M  
205  0.0036  0.0048  M  
206  0.0061  0.0115  M  

[207 rows x 61 columns]

In [3]:
df.shape

(207, 61)

In [4]:
df.isnull().sum() # So this Dataset does'nt have any null values.

0.02      0
0.0371    0
0.0428    0
0.0207    0
0.0954    0
         ..
0.018     0
0.0084    0
0.009     0
0.0032    0
R         0
Length: 61, dtype: int64

In [5]:
df.columns

Index(['0.02', '0.0371', '0.0428', '0.0207', '0.0954', '0.0986', '0.1539',
       '0.1601', '0.3109', '0.2111', '0.1609', '0.1582', '0.2238', '0.0645',
       '0.066', '0.2273', '0.31', '0.2999', '0.5078', '0.4797', '0.5783',
       '0.5071', '0.4328', '0.555', '0.6711', '0.6415', '0.7104', '0.808',
       '0.6791', '0.3857', '0.1307', '0.2604', '0.5121', '0.7547', '0.8537',
       '0.8507', '0.6692', '0.6097', '0.4943', '0.2744', '0.051', '0.2834',
       '0.2825', '0.4256', '0.2641', '0.1386', '0.1051', '0.1343', '0.0383',
       '0.0324', '0.0232', '0.0027', '0.0065', '0.0159', '0.0072', '0.0167',
       '0.018', '0.0084', '0.009', '0.0032', 'R'],
      dtype='object')

In [6]:
df['R'].value_counts()

M    111
R     96
Name: R, dtype: int64

In [7]:
x = df.drop('R', axis =1)
y = df['R']
y.head()

0    R
1    R
2    R
3    R
4    R
Name: R, dtype: object

In [8]:
# Now we will be doing one-hot encoding on this column and that will give two more columns for R (rock) and M(Metal)
# But here we will be dropping one column, because there are one two values and 0 means rock and 1 means metal
# WE CAN ALSO DO THE LABEL ENCODING HERE
y = pd.get_dummies(y, drop_first = True)
y.sample(5) # You See here 1 means yes a rock and 0 means its a metal.

R
56   1
144  0
8    1
77   1
89   1

In [9]:
y.value_counts()

R
0    111
1     96
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.25, random_state = 1)

In [11]:
x_train.shape, x_test.shape

((155, 60), (52, 60))

In [12]:
import tensorflow as tf
from tensorflow import keras

In [13]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation = 'relu'), #first dense layer consisting of the input layer of 60 nuerons because of the 60 columns and a hidden layer of 60 nuerons as well
    keras.layers.Dense(30, activation = 'relu'),# Second hidden layer
    keras.layers.Dense(15, activation = 'relu'),# 3rd gidden layer 
    keras.layers.Dense(1, activation = 'sigmoid'),# Output Layer
])
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics= 'accuracy') # The loss is binary because we have the values as 0 and 1
model.fit(x_train, y_train, epochs =100, batch_size =8) # batch_size is using a mini batch of 8 samples and fitting that in our ANN
                                                        # model and runing 100 epochs, we will find that we receive an accracy of 1, that means that the dataset is overfitted and we will have a low test accuracy


Epoch 1/100
20/20 [==============================] - 1s 3ms/step - loss: 0.6797 - accuracy: 0.6065
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6489 - accuracy: 0.6903
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6214 - accuracy: 0.7097
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5993 - accuracy: 0.7290
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5568 - accuracy: 0.7613
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5310 - accuracy: 0.7419
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5176 - accuracy: 0.7613
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4773 - accuracy: 0.8065
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4605 - accuracy: 0.8000
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4280 - accuracy: 0.7677
Epoch 11/

In [14]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.8707 - accuracy: 0.8462


[0.8706709146499634, 0.8461538553237915]

In [15]:
model.predict(x_test)

2/2 [==============================] - 0s 0s/step


array([[2.3468630e-04],
       [4.1190669e-05],
       [2.0043117e-03],
       [1.7415085e-04],
       [9.9999613e-01],
       [9.3573406e-03],
       [9.5281827e-01],
       [1.1458845e-04],
       [1.5235477e-04],
       [9.9997419e-01],
       [9.9992967e-01],
       [9.5163608e-01],
       [1.9414206e-04],
       [2.0031361e-03],
       [1.3739608e-01],
       [3.4516981e-01],
       [9.4086313e-01],
       [4.7498380e-04],
       [9.9937010e-01],
       [9.9999988e-01],
       [4.4819684e-05],
       [9.9982274e-01],
       [9.9909008e-01],
       [7.4199005e-04],
       [1.2928760e-01],
       [8.5890677e-04],
       [9.9999905e-01],
       [9.9225074e-01],
       [9.9861199e-01],
       [1.0924387e-02],
       [2.3775351e-01],
       [7.8549019e-06],
       [1.2865837e-01],
       [5.7675410e-04],
       [9.9967402e-01],
       [9.5059305e-02],
       [9.9999511e-01],
       [8.1230002e-04],
       [9.9987441e-01],
       [2.2739905e-01],
       [1.6853042e-01],
       [4.882374

In [16]:
y_pred = model.predict(x_test).reshape(-1)
y_pred # Here we are changing the shape of the array to a 1D array and now we will be rounding off the values of the the y_pred
# since the values of y_pred are between 0 and 1 so rounding off will give either 1 or 0
y_pred = np.round(y_pred)
y_pred

2/2 [==============================] - 0s 0s/step


array([0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0.], dtype=float32)

In [17]:
y_test, y_pred

(     R
 186  0
 155  0
 165  0
 200  0
 58   1
 34   1
 151  0
 18   1
 202  0
 62   1
 4    1
 47   1
 110  0
 205  0
 105  0
 172  0
 31   1
 198  0
 33   1
 40   1
 175  0
 59   1
 29   1
 11   1
 124  0
 147  0
 35   1
 44   1
 51   1
 171  0
 153  0
 183  0
 28   1
 16   1
 94   1
 78   1
 38   1
 27   1
 69   1
 119  0
 206  0
 191  0
 73   1
 166  0
 138  0
 199  0
 84   1
 90   1
 123  0
 169  0
 107  0
 201  0,
 array([0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
        0.], dtype=float32))

In [18]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
cm

array([[26,  1],
       [ 7, 18]], dtype=int64)

In [19]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.79      0.96      0.87        27
           1       0.95      0.72      0.82        25

    accuracy                           0.85        52
   macro avg       0.87      0.84      0.84        52
weighted avg       0.86      0.85      0.84        52



In [20]:
# So now we will be adding the dropout layers and check the accuracy again for the new ANN
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation = 'relu'), #first dense layer consisting of the input layer of 60 nuerons because of the 60 columns and a hidden layer of 60 nuerons as well
    keras.layers.Dropout(0.5),# 50% of the nuerons will turn off randomly -- first dropout layer
    keras.layers.Dense(30, activation = 'relu'),# Second hidden layer
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation = 'relu'),# 3rd gidden layer 
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation = 'sigmoid'),# Output Layer
])
modeld.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics= 'accuracy') # The loss is binary because we have the values as 0 and 1
modeld.fit(x_train, y_train, epochs =100, batch_size =8) # batch_size is using a mini batch of 8 samples and fitting that in our ANN
                                                        # model and runing 100 epochs, we will find that we receive an accracy of 1, that means that the dataset is overfitted and we will have a low test accuracy


Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6720 - accuracy: 0.5935
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7357 - accuracy: 0.5097
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7058 - accuracy: 0.5290
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7201 - accuracy: 0.5355
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7170 - accuracy: 0.4645
Epoch 6/100
20/20 [==============================] - 0s 881us/step - loss: 0.6704 - accuracy: 0.6258
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6972 - accuracy: 0.5161
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6415 - accuracy: 0.6129
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6851 - accuracy: 0.5290
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6770 - accuracy: 0.5161
Epoch 1

In [21]:
# Clearly the model has not reached 100% accuracy and thus not overfitted
modeld.evaluate(x_test,y_test)

2/2 [==============================] - 0s 18ms/step - loss: 0.4036 - accuracy: 0.8269


[0.40362322330474854, 0.8269230723381042]

In [22]:
# Clearly the test accuracy has increased after using the Dropout layers.

In [23]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.79      0.96      0.87        27
           1       0.95      0.72      0.82        25

    accuracy                           0.85        52
   macro avg       0.87      0.84      0.84        52
weighted avg       0.86      0.85      0.84        52

